// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjB2sUoWR5aljYzGtbM62zRw75krD5orQ',
    appId: '1:331475033786:web:a1838bdeec1ff9a8386c83',
    messagingSenderId: '331475033786',
    projectId: 'plantguard-ai-14e41',
    authDomain: 'plantguard-ai-14e41.firebaseapp.com',
    storageBucket: 'plantguard-ai-14e41.firebasestorage.app',
    measurementId: 'G-QG1G0776HM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLQjuNt6YN3jvrhYvWP82x1KavYO_okJg',
    appId: '1:331475033786:android:c0e1b6f827b295a4386c83',
    messagingSenderId: '331475033786',
    projectId: 'plantguard-ai-14e41',
    storageBucket: 'plantguard-ai-14e41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQT00RUe9aawQ6zuwS02CKDDC0xxSQ12o',
    appId: '1:331475033786:ios:bec0cec3ee0acb67386c83',
    messagingSenderId: '331475033786',
    projectId: 'plantguard-ai-14e41',
    storageBucket: 'plantguard-ai-14e41.firebasestorage.app',
    iosBundleId: 'com.example.plantguardAi',
  );
}
